name: push handler
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3'
      - name: Build code
        run: make build
        env:
          BUILDROOT: /tmp/build_checkpg
  test:
    runs-on: ubuntu-latest
    #needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3'
      - run: make test
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3'
      - name: Run GolangCI-Lint
        uses: golangci/golangci-lint-action@v2
        with:
          args: --config=.golangci.yml

